[package]
name = "videostream"
version = "0.1.0"
authors = ["Ashley <expenses@airmail.cc>"]

[dependencies]
image = "*"
ffmpeg = {git = "https://github.com/meh/rust-ffmpeg"}
rayon = "*"

[dev-dependencies]
rustface = "*"